POST http://localhost:8000/update-data
Content-Type: application/json

{
    "table_name": "events",
    "upsert": [
        {
            "user_id": 1,
            "event_id": 1,
            "event": {
                "event_type": "click",
                "lang": "ru",
                "offer_id": 1
            }
        },
        {
            "user_id": 1,
            "event_id": 2,
            "event": {
                "event_type": "click",
                "lang": "ru",
                "offer_id": 2
            }
        },
        {
            "user_id": 2,
            "event_id": 1,
            "event": {
                "event_type": "click",
                "lang": "ru",
                "offer_id": 1
            }
        },
        {
            "user_id": 2,
            "event_id": 2,
            "event": {
                "event_type": "click",
                "lang": "en",
                "offer_id": 2
            }
        },
        {
            "user_id": 3,
            "event_id": 1,
            "event": {
                "event_type": "click",
                "lang": "ru",
                "offer_id": 1
            }
        },
        {
            "user_id": 3,
            "event_id": 2,
            "event": {
                "event_type": "click",
                "lang": "de",
                "offer_id": 2
            }
        },
        {
            "user_id": 4,
            "event_id": 1,
            "event": {
                "event_type": "click",
                "lang": "ru",
                "offer_id": 1
            }
        },
        {
            "user_id": 4,
            "event_id": 2,
            "event": {
                "event_type": "click",
                "lang": "fr",
                "offer_id": 2
            }
        }
    ]
}

###
POST http://localhost:8000/update-data
Content-Type: application/json

{
    "table_name": "events",
    "delete": [
        {
            "user_id": 1,
            "event_id": 1
        }
    ]
}

###
POST http://localhost:8000/get-data
Content-Type: application/json

{
    "table_name": "events",
    "idx": [
        {"user_id": 10}
    ]
}

###
GET http://localhost:8000/get-data?table=user_lang
